# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('frontend/out', 'frontend/out'),
        ('backend', 'backend'),
    ],
    hiddenimports=[
        'backend',
        'backend.main',
        'backend.config',
        'backend.routes',
        'backend.routes.clip',
        'backend.routes.caption',
        'backend.routes.render',
        'backend.downloader',
        'backend.processor',
        'backend.caption',
        'backend.utils',
        'backend.worker',
        'stable_whisper',
        'whisper',
        'torch',
        'torchaudio',
        'fastapi',
        'uvicorn',
        'pydantic',
        'static_ffmpeg',
        'yt_dlp',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludedimports=[],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ClipCuy',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
